version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rce_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./rce
    container_name: backend
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rce_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      FRONTEND_ORIGIN: http://localhost:3001
      GITHUB_CLIENT_ID: 
      GITHUB_CLIENT_SECRET: 
      JUDGE0_API_KEY: 

  frontend:
    build:
      context: ./leetcode-ui
    container_name: frontend
    restart: on-failure
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  mysql-data:
